# Generated by Django 4.0.3 on 2022-03-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_holder',
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='app.user'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
