# Generated by Django 4.0.3 on 2022-03-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_account_account_holder_account_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owner_id',
            field=models.ForeignKey(db_column="owner_id", on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
