# Generated by Django 4.0.3 on 2022-03-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.FloatField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
