# Generated by Django 4.0.3 on 2022-04-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_account_account_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='balance_currency',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
