image: docker/compose:alpine-1.28.0


stages:
  - build
  - lint
  - test
  - deploy

before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cat $DOT_ENV > $(pwd)/.env

build:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  only:
    - master
  environment:
    name: prod

lint:
  stage: lint
  script:
    - make pull check_lint
  tags:
    - job:lint
  only:
    - master
  environment:
    name: prod

test:
  stage: test
  script:
    - make pull test
  tags:
    - job:test
  only:
    - master
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - make pull down migrate up
  tags:
    - job:deploy
  only:
    - master
  environment:
    name: prod
  when: manual