version: "3.3"

services:
  bot:
    container_name: doubletapp-bot
    image: "${IMAGE_APP}"
    build: .
    env_file:
      - .env
    command: python src/manage.py runbot
    depends_on:
      - db

  app:
    container_name: doubletapp-app
    image: "${IMAGE_APP}"
    build: .
    env_file:
      - .env
    command: >
      bash -c "bash entrypoint.sh &&
               python src/manage.py migrate &&
               python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - "${HOST_PORT}:8000"
    depends_on:
      - db

  db:
    container_name: doubletapp_db
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
